version: '3.8'

services:
    web:
        build: .
        command: gunicorn --bind=0.0.0.0:8080 src.api:app
        ports:
            - 8080:8080
        environment:
            - DEBUG
            - DB_HOST
            - DB_USER
            - DB_PWD
            - DB_NAME
            - MAIL_PASSWORD
            - RECAPTCHA_PUBLIC_KEY
            - RECAPTCHA_PRIVATE_KEY
            - ZENODO_ACCESS_KEY
