version: '3.8'

services:
    web:
        build: .
        command: gunicorn --bind=0.0.0.0:8080 src.api:app --timeout=1000
        ports:
            - 8080:8080
        environment:
            - DEBUG
            - DB_HOST
            - DB_USER
            - DB_PWD
            - DB_NAME
            - MAIL_PASSWORD
            - RECAPTCHA_PUBLIC_KEY
            - RECAPTCHA_PRIVATE_KEY
            - ZENODO_ACCESS_KEY
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AWS_BUCKET
    worker:
        build: .
        command: celery -A src.tasks.celery worker
        environment:
            - DEBUG
            - DB_HOST
            - DB_USER
            - DB_PWD
            - DB_NAME
            - MAIL_PASSWORD
            - RECAPTCHA_PUBLIC_KEY
            - RECAPTCHA_PRIVATE_KEY
            - ZENODO_ACCESS_KEY
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION
            - AWS_BUCKET
